import { Color, ColorAlternative, FontFamily, FontSize, Palette } from './theme';
declare const CommonStyle: import("styled-components").FlattenInterpolation<import("styled-components").ThemedStyledProps<Record<string, unknown> & import("styled-components").ThemeProps<import("./theme").Theme>, any>>;
declare const placeholderStyle: import("styled-components").FlattenSimpleInterpolation;
declare const color: Color;
declare const colorAlternative: ColorAlternative;
declare const fontSize: FontSize;
declare const palette: Palette;
declare const fontFamily: FontFamily;
declare const BrandedPath: import("styled-components").StyledComponent<"path", any, Record<string, unknown> & import("styled-components").ThemeProps<import("./theme").Theme>, never>;
declare const SkeletonPlaceholder: import("styled-components").StyledComponent<"div", any, {}, never>;
export { color, colorAlternative, fontFamily, fontSize, palette, CommonStyle, BrandedPath, SkeletonPlaceholder, placeholderStyle, };
