import React, { ReactElement, ReactNode } from 'react';
type TableInputSelectProps = {
    value: ReactNode | null;
    onClear: () => void;
    highlighted?: boolean;
    clearLabel: string;
    openDropdownLabel: string;
    onNextPage?: () => void;
    searchValue?: string;
    onSearchChange?: (search: string) => void;
    searchPlaceholder: string;
    searchTitle: string;
    inError?: boolean;
    closeTick?: boolean;
    bottomHelper?: ReactElement;
    withSearch?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
    children?: ReactNode;
};
declare const TableInputSelect: React.FC<TableInputSelectProps>;
export { TableInputSelect };
