"use strict";var P=Object.defineProperty,k=Object.defineProperties;var I=Object.getOwnPropertyDescriptors;var l=Object.getOwnPropertySymbols;var C=Object.prototype.hasOwnProperty,g=Object.prototype.propertyIsEnumerable;var v=(e,r,t)=>r in e?P(e,r,{enumerable:!0,configurable:!0,writable:!0,value:t}):e[r]=t,h=(e,r)=>{for(var t in r||(r={}))C.call(r,t)&&v(e,t,r[t]);if(l)for(var t of l(r))g.call(r,t)&&v(e,t,r[t]);return e},p=(e,r)=>k(e,I(r));var x=(e,r)=>{var t={};for(var o in e)C.call(e,o)&&r.indexOf(o)<0&&(t[o]=e[o]);if(e!=null&&l)for(var o of l(e))r.indexOf(o)<0&&g.call(e,o)&&(t[o]=e[o]);return t};var y=require("react/jsx-runtime"),R=require("../../../shared/key.js"),i=require("react"),K=require("styled-components"),j=require("../../../hooks/useAutoFocus.js"),E=require("../../../hooks/useCombinedRefs.js"),F=require("../../../hooks/usePagination.js"),S=require("../../Placeholder/Placeholder.js"),z=require("../../../theme/theme.js");function q(e){return e&&e.__esModule?e:{default:e}}var T=q(i),w=q(K);const V=w.default.div`
  max-height: 320px;
  overflow-y: auto;
  overflow-x: hidden;
`,M=w.default(S.Placeholder)`
  margin: 10px 10px 20px 10px;
  & > div {
    font-size: ${z.getFontSize("default")};
  }
`,N=T.default.forwardRef((U,b)=>{var a=U,{children:e,onNextPage:r,noResultTitle:t,noResultIllustration:o}=a,_=x(a,["children","onNextPage","noResultTitle","noResultIllustration"]);const s=i.useRef(null),f=i.useRef(null),c=E.useCombinedRefs(b),D=i.useCallback(n=>{var u,m;n.currentTarget!==null&&(n.key===R.Key.ArrowDown&&((u=n.currentTarget.nextSibling)==null||u.focus(),n.preventDefault()),n.key===R.Key.ArrowUp&&((m=n.currentTarget.previousSibling)==null||m.focus(),n.preventDefault()))},[]),d=i.Children.toArray(e).filter(i.isValidElement).length,A=i.Children.map(e,(n,u)=>i.isValidElement(n)?i.cloneElement(n,{ref:u===0?s:u===d-1?f:void 0,onKeyDown:D}):n);return F.usePagination(c,f,r,!0),j.useAutoFocus(s),y.jsx(V,p(h({role:"listbox"},_),{ref:c,children:d?A:o&&t&&y.jsx(M,{illustration:o,title:t})}))});exports.ItemCollection=N;
