"use strict";var P=Object.defineProperty,j=Object.defineProperties;var k=Object.getOwnPropertyDescriptors;var a=Object.getOwnPropertySymbols;var x=Object.prototype.hasOwnProperty,h=Object.prototype.propertyIsEnumerable;var v=(e,r,t)=>r in e?P(e,r,{enumerable:!0,configurable:!0,writable:!0,value:t}):e[r]=t,C=(e,r)=>{for(var t in r||(r={}))x.call(r,t)&&v(e,t,r[t]);if(a)for(var t of a(r))h.call(r,t)&&v(e,t,r[t]);return e},g=(e,r)=>j(e,k(r));var p=(e,r)=>{var t={};for(var n in e)x.call(e,n)&&r.indexOf(n)<0&&(t[n]=e[n]);if(e!=null&&a)for(var n of a(e))r.indexOf(n)<0&&h.call(e,n)&&(t[n]=e[n]);return t};var l=require("react/jsx-runtime"),y=require("../../../shared/key.js"),o=require("react"),K=require("styled-components"),E=require("../../../hooks/useAutoFocus.js"),F=require("../../../hooks/useCombinedRefs.js"),I=require("../../../hooks/usePagination.js"),S=require("../../Placeholder/Placeholder.js"),z=require("../../../theme/theme.js");function R(e){return e&&e.__esModule?e:{default:e}}var T=R(o),q=R(K);const V=q.default.div`
  max-height: 320px;
  overflow-y: auto;
  overflow-x: hidden;
`,M=q.default(S.Placeholder)`
  margin: 10px 10px 20px 10px;
  & > div {
    font-size: ${z.getFontSize("default")};
  }
`,N=T.default.forwardRef((U,_)=>{var s=U,{children:e,onNextPage:r,noResultTitle:t,noResultIllustration:n}=s,w=p(s,["children","onNextPage","noResultTitle","noResultIllustration"]);const f=o.useRef(null),d=o.useRef(null),c=F.useCombinedRefs(_),b=o.useCallback(i=>{var u,m;i.currentTarget!==null&&(i.key===y.Key.ArrowDown&&((u=i.currentTarget.nextSibling)==null||u.focus(),i.preventDefault()),i.key===y.Key.ArrowUp&&((m=i.currentTarget.previousSibling)==null||m.focus(),i.preventDefault()))},[]),D=o.Children.toArray(e).filter(o.isValidElement).length,A=o.Children.map(e,(i,u)=>o.isValidElement(i)?o.cloneElement(i,{ref:u===0?f:void 0,onKeyDown:b}):i);return I.usePagination(c,d,r,!0),E.useAutoFocus(f),l.jsxs(V,g(C({role:"listbox"},w),{ref:c,children:[D?A:n&&t&&l.jsx(M,{illustration:n,title:t}),l.jsx("div",{ref:d,"aria-hidden":"true"})]}))});exports.ItemCollection=N;
