name: Deploy
on:
  push:
    branches:
      - master
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v2

      - name: Install node for the rest of the workflow
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install node modules
        run: npm ci

      - name: Build storybook
        run: npm run storybook:build

      - name: Add cleanup staging script
        run: |
          mkdir -p ./storybook-static/.github/workflows && \
          cp ./.github/workflows/cleanup-staging.js ./storybook-static/.github/workflows/cleanup-staging.js

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          exclude_assets: ''
