name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: 'read'
  pull-requests: 'write'
  issues: 'write'

jobs:
  compliance-checks:
    uses: ./.github/workflows/security-scan.yml
